"""985院校列表。"""

UNIVERSITIES_985 = [
    {"name": "北京大学", "code": "pku"},
    {"name": "清华大学", "code": "tsinghua"},
    {"name": "中国人民大学", "code": "ruc"},
    {"name": "北京航空航天大学", "code": "buaa"},
    {"name": "北京理工大学", "code": "bit"},
    {"name": "北京师范大学", "code": "bnu"},
    {"name": "中央民族大学", "code": "muc"},
    {"name": "中国农业大学", "code": "cau"},
    {"name": "天津大学", "code": "tju"},
    {"name": "南开大学", "code": "nankai"},
    {"name": "大连理工大学", "code": "dlut"},
    {"name": "东北大学", "code": "neu"},
    {"name": "吉林大学", "code": "jlu"},
    {"name": "哈尔滨工业大学", "code": "hit"},
    {"name": "复旦大学", "code": "fudan"},
    {"name": "上海交通大学", "code": "sjtu"},
    {"name": "同济大学", "code": "tongji"},
    {"name": "华东师范大学", "code": "ecnu"},
    {"name": "南京大学", "code": "nju"},
    {"name": "东南大学", "code": "seu"},
    {"name": "浙江大学", "code": "zju"},
    {"name": "中国科学技术大学", "code": "ustc"},
    {"name": "厦门大学", "code": "xmu"},
    {"name": "山东大学", "code": "sdu"},
    {"name": "中国海洋大学", "code": "ouc"},
    {"name": "武汉大学", "code": "whu"},
    {"name": "华中科技大学", "code": "hust"},
    {"name": "中南大学", "code": "csu"},
    {"name": "湖南大学", "code": "hnu"},
    {"name": "国防科技大学", "code": "nudt"},
    {"name": "中山大学", "code": "sysu"},
    {"name": "华南理工大学", "code": "scut"},
    {"name": "四川大学", "code": "scu"},
    {"name": "电子科技大学", "code": "uestc"},
    {"name": "重庆大学", "code": "cqu"},
    {"name": "西安交通大学", "code": "xjtu"},
    {"name": "西北工业大学", "code": "nwpu"},
    {"name": "兰州大学", "code": "lzu"},
    {"name": "西北农林科技大学", "code": "nwafu"},
]
